sudo: required
services:
  - docker

script:
  - docker build -t smartdatasolutions/node .
  - docker images smartdatasolutions/node 

before_deploy:
  - docker login -u 'smartdatasolutions' -p '#Dk122616053'

deploy:
  provider: script
  script: docker push smartdatasolutions/node
  on:
    branch: master